server:
  port: 8080

spring:
  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/market?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
#    driver-class-name: com.mysql.jdbc.Driver
    #### 可写数据源
    update:
      jdbc-url: jdbc:mysql://localhost:3316/db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:
    #### 可读数据源
    select:
      jdbc-url: jdbc:mysql://localhost:3326/db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wzj.spring01.entity

logging:
  level:
    com:
      wzj:
        spring01 : debug
